# Generated by Django 3.2.10 on 2021-12-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translate", "0002_delete_activelanguage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[("en", "en"), ("fr", "fr")], max_length=254
            ),
        ),
    ]
