# Generated by Django 3.2.10 on 2022-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_orderlineitem_lineitem_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="lineItem_vat",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="lineitem_total",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
