# Generated by Django 3.2.10 on 2022-01-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_auto_20220106_1905"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="colour",
            field=models.CharField(default="none", max_length=254),
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="size",
            field=models.CharField(default="none", max_length=254),
        ),
    ]
