# Generated by Django 3.2.10 on 2022-01-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_auto_20220113_0754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="gross_total",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="net_total",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="order",
            name="vat",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
