# Generated by Django 3.2.10 on 2021-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="has_colour",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_sizes",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="has_vat",
            field=models.BooleanField(default=False),
        ),
    ]
