# Generated by Django 3.2.10 on 2021-12-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20211228_0925"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_colour",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_sizes",
        ),
    ]
